import type { Metadata } from 'next';
import { Html, Head, Main, NextScript } from 'next/document';

import { ToastContainer } from 'react-toastify';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Document() {
  return (
    <Html lang="en">
      <Head />
      <body>
        <Main />
        <ToastContainer
          position="top-left"
          className="z-100" />
        <NextScript />
      </body>
    </Html>
  );
}
