"use client";

import '@unocss/reset/tailwind.css';
import '@unocss/reset/sanitize/assets.css';
import '@unocss/reset/sanitize/sanitize.css';
import '@uiw/react-markdown-preview/markdown.css';
import '@uiw/react-md-editor/markdown-editor.css';
import 'react-toastify/ReactToastify.css';

import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';


import { ToastContainer } from 'react-toastify';

import './globals.css';
import Context from './context';

const defaultFont = Noto_Sans({
  subsets: ['latin'],
  weight: ["300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body className={defaultFont.className.concat(" fixed inset-0 flex flex-col text-[15px]")}>
        <Context>
          {children}
        </Context>
        <ToastContainer 
          position="top-left"
          className="z-100" />
      </body>
    </html>
  );
}
